//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System.ComponentModel.DataAnnotations;

    public partial class IS_Employees
    {
        [Required]
        public string WorkdayID { get; set; }
        [Required]
        public string EmployeeName { get; set; }
        [Required]
        public string EmployeeTeam { get; set; }
        [Required]
        public string EmployeeTeamLeader { get; set; }
    }
}
