//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    public partial class IS_Events
    {
        public long EventID { get; set; }
        public string EventName { get; set; }
        public string EventDate { get; set; }
        public string EventLocation { get; set; }
    }
}
